// Code generated by 'yaegi extract github.com/jpl-au/llmd/sdk'. DO NOT EDIT.

package plugin

import (
	"reflect"

	"github.com/traefik/yaegi/interp"

	"github.com/jpl-au/llmd/sdk"
)

// symbols returns Yaegi exports for the sdk package.
// Plugins import "github.com/jpl-au/llmd/sdk" and get these symbols.
func symbols() interp.Exports {
	return interp.Exports{
		"github.com/jpl-au/llmd/sdk/sdk": {
			// function, constant and variable definitions
			"API":          reflect.ValueOf(&sdk.API).Elem(),
			"GrepFull":     reflect.ValueOf(sdk.GrepFull),
			"GrepLines":    reflect.ValueOf(sdk.GrepLines),
			"GrepPaths":    reflect.ValueOf(sdk.GrepPaths),
			"GrepSections": reflect.ValueOf(sdk.GrepSections),
			"GrepSnippets": reflect.ValueOf(sdk.GrepSnippets),

			// type definitions
			"Command":  reflect.ValueOf((*sdk.Command)(nil)),
			"Context":  reflect.ValueOf((*sdk.Context)(nil)),
			"Data":     reflect.ValueOf((*sdk.Data)(nil)),
			"Doc":      reflect.ValueOf((*sdk.Doc)(nil)),
			"Flag":     reflect.ValueOf((*sdk.Flag)(nil)),
			"GrepHit":  reflect.ValueOf((*sdk.GrepHit)(nil)),
			"GrepMode": reflect.ValueOf((*sdk.GrepMode)(nil)),
			"GrepOpts": reflect.ValueOf((*sdk.GrepOpts)(nil)),
			"ListOpts": reflect.ValueOf((*sdk.ListOpts)(nil)),
			"Plugin":   reflect.ValueOf((*sdk.Plugin)(nil)),
			"Response": reflect.ValueOf((*sdk.Response)(nil)),
			"Result":   reflect.ValueOf((*sdk.Result)(nil)),
			"Store":    reflect.ValueOf((*sdk.Store)(nil)),
			"Text":     reflect.ValueOf((*sdk.Text)(nil)),
			"Version":  reflect.ValueOf((*sdk.Version)(nil)),

			// interface wrapper definitions
			"_Plugin":   reflect.ValueOf((*_github_com_jpl_au_llmd_sdk_Plugin)(nil)),
			"_Response": reflect.ValueOf((*_github_com_jpl_au_llmd_sdk_Response)(nil)),
			"_Store":    reflect.ValueOf((*_github_com_jpl_au_llmd_sdk_Store)(nil)),
		},
	}
}

// _github_com_jpl_au_llmd_sdk_Plugin is an interface wrapper for Plugin type
type _github_com_jpl_au_llmd_sdk_Plugin struct {
	IValue    interface{}
	WCommands func() []sdk.Command
	WExec     func(ctx sdk.Context, cmd string, args []string) (sdk.Response, error)
	WName     func() string
}

func (W _github_com_jpl_au_llmd_sdk_Plugin) Commands() []sdk.Command {
	return W.WCommands()
}
func (W _github_com_jpl_au_llmd_sdk_Plugin) Exec(ctx sdk.Context, cmd string, args []string) (sdk.Response, error) {
	return W.WExec(ctx, cmd, args)
}
func (W _github_com_jpl_au_llmd_sdk_Plugin) Name() string {
	return W.WName()
}

// _github_com_jpl_au_llmd_sdk_Response is an interface wrapper for Response type
type _github_com_jpl_au_llmd_sdk_Response struct {
	IValue    interface{}
	WResponse func()
}

func (W _github_com_jpl_au_llmd_sdk_Response) Response() {
	W.WResponse()
}

// _github_com_jpl_au_llmd_sdk_Store is an interface wrapper for Store type
type _github_com_jpl_au_llmd_sdk_Store struct {
	IValue   interface{}
	WDelete  func(path string, author string) error
	WDiff    func(a string, b string, ctx int) (string, int, int, error)
	WEdit    func(path string, old string, new string, author string, msg string) error
	WExists  func(path string) (bool, error)
	WGlob    func(pattern string) ([]string, error)
	WGrep    func(query string, opts sdk.GrepOpts) ([]sdk.GrepHit, error)
	WHistory func(path string, limit int) ([]sdk.Version, error)
	WList    func(prefix string, opts sdk.ListOpts) ([]sdk.Doc, error)
	WMove    func(from string, to string, author string) error
	WRead    func(path string, version int) ([]byte, error)
	WRestore func(path string, author string) error
	WRevert  func(path string, version int, author string, msg string) error
	WWrite   func(path string, content []byte, author string, msg string) error
}

func (W _github_com_jpl_au_llmd_sdk_Store) Delete(path string, author string) error {
	return W.WDelete(path, author)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Diff(a string, b string, ctx int) (string, int, int, error) {
	return W.WDiff(a, b, ctx)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Edit(path string, old string, new string, author string, msg string) error {
	return W.WEdit(path, old, new, author, msg)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Exists(path string) (bool, error) {
	return W.WExists(path)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Glob(pattern string) ([]string, error) {
	return W.WGlob(pattern)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Grep(query string, opts sdk.GrepOpts) ([]sdk.GrepHit, error) {
	return W.WGrep(query, opts)
}
func (W _github_com_jpl_au_llmd_sdk_Store) History(path string, limit int) ([]sdk.Version, error) {
	return W.WHistory(path, limit)
}
func (W _github_com_jpl_au_llmd_sdk_Store) List(prefix string, opts sdk.ListOpts) ([]sdk.Doc, error) {
	return W.WList(prefix, opts)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Move(from string, to string, author string) error {
	return W.WMove(from, to, author)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Read(path string, version int) ([]byte, error) {
	return W.WRead(path, version)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Restore(path string, author string) error {
	return W.WRestore(path, author)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Revert(path string, version int, author string, msg string) error {
	return W.WRevert(path, version, author, msg)
}
func (W _github_com_jpl_au_llmd_sdk_Store) Write(path string, content []byte, author string, msg string) error {
	return W.WWrite(path, content, author, msg)
}
