#!/bin/bash
# Generated by llmd for agent task execution.
# This wrapper runs the agent and handles task lifecycle:
#   1. Runs the agent command
#   2. On exit, checks if the task was already moved (by hooks)
#   3. If not, moves the task based on exit code using rule transitions
#   4. Records run completion (stats, cost, tokens)
#
# Transport: HTTP API first (if LLMD_URL is set), CLI fallback.
# Template variables are replaced by llmd at spawn time.

TASK_ID="{{.TaskID}}"
AGENT="{{.Agent}}"
ROLE="{{.Role}}"
LLMD="{{.LLMD}}"
LLMD_URL="{{.URL}}"
WORKTREE="{{.Worktree}}"

# Transitions from the rule. Always set at spawn time.
ON_SUCCESS="{{.OnSuccess}}"
ON_FAILURE="{{.OnFailure}}"

# task_move moves a task to the given column. Tries HTTP then CLI.
task_move() {
  local col="$1"
  if [ -z "${col}" ]; then
    return 0
  fi
  if [ -n "${LLMD_URL}" ]; then
    curl -sf -X POST "${LLMD_URL}/task/move/${TASK_ID}/${col}" \
      -H "Author: ${AGENT}" 2>/dev/null && return 0
  fi
  "${LLMD}" --author "${AGENT}" task move "${TASK_ID}" "${col}" 2>/dev/null
}

# task_status returns the current task status. Tries HTTP then CLI.
task_status() {
  if [ -n "${LLMD_URL}" ]; then
    local resp
    resp=$(curl -sf "${LLMD_URL}/task/show/${TASK_ID}" -H "Output: json" 2>/dev/null)
    if [ -n "${resp}" ]; then
      echo "${resp}" | grep -oi '"Status":"[^"]*"' | head -1 | cut -d'"' -f4
      return 0
    fi
  fi
  "${LLMD}" task show "${TASK_ID}" --json 2>/dev/null | grep -oi '"Status":"[^"]*"' | head -1 | cut -d'"' -f4
}

# agent_complete records run completion with stats extracted from
# the agent's output log.
agent_complete() {
  local exit_code="$1"
  "${LLMD}" --author "${AGENT}" agent complete "${TASK_ID}" --exit-code "${exit_code}" 2>/dev/null
}

# Run the agent.
cd "${WORKTREE}"
{{.Command}} {{.Args}}
EXIT=$?

# Auditors handle their own lifecycle moves via the prompt template.
# Developers and testers get automatic moves from the wrapper.
if [ "${ROLE}" != "auditor" ]; then
  STATUS=$(task_status || echo "unknown")

  if [ "${STATUS}" = "in-progress" ] || [ "${STATUS}" = "${ROLE}" ] || [ "${STATUS}" = "unknown" ]; then
    if [ ${EXIT} -eq 0 ]; then
      task_move "${ON_SUCCESS}" || true
    else
      task_move "${ON_FAILURE}" || true
    fi
  fi
fi

# Record run completion (extracts stats from the agent log).
agent_complete ${EXIT}

exit ${EXIT}
