// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.12
// source: host/host.proto

package host

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

// Document messages
type ReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version *int32 `protobuf:"varint,2,opt,name=version,proto3,oneof" json:"version,omitempty"`
}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author  string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *WriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *WriteRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	OldText string `protobuf:"bytes,2,opt,name=old_text,json=oldText,proto3" json:"old_text,omitempty"`
	NewText string `protobuf:"bytes,3,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	Author  string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *EditRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *EditRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EditRequest) GetOldText() string {
	if x != nil {
		return x.OldText
	}
	return ""
}

func (x *EditRequest) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

func (x *EditRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *EditRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type RestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RestoreRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RestoreRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix         string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	IncludeDeleted bool   `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	Sort           string `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Reverse        bool   `protobuf:"varint,4,opt,name=reverse,proto3" json:"reverse,omitempty"`
}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

func (x *ListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Dest   string `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *MoveRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MoveRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *MoveRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type ExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExistsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content   []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Version   int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Author    string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Message   string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt int64  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Deleted   bool   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *Document) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Document) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Document) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Document) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Document) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Document) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Document) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Document) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type DocumentListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Documents []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
}

func (x *DocumentListResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DocumentListResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Search messages
type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Prefix string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type SearchResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*SearchMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *SearchResults) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SearchResults) GetMatches() []*SearchMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type SearchMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Snippet string  `protobuf:"bytes,2,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score   float32 `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *SearchMatch) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SearchMatch) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SearchMatch) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *SearchMatch) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GrepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern      string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Path         string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IgnoreCase   bool   `protobuf:"varint,3,opt,name=ignore_case,json=ignoreCase,proto3" json:"ignore_case,omitempty"`
	ContextLines int32  `protobuf:"varint,4,opt,name=context_lines,json=contextLines,proto3" json:"context_lines,omitempty"`
}

func (x *GrepRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GrepRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *GrepRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GrepRequest) GetIgnoreCase() bool {
	if x != nil {
		return x.IgnoreCase
	}
	return false
}

func (x *GrepRequest) GetContextLines() int32 {
	if x != nil {
		return x.ContextLines
	}
	return 0
}

type GrepResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*GrepMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *GrepResults) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GrepResults) GetMatches() []*GrepMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type GrepMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path          string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Line          int32    `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Content       string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContextBefore []string `protobuf:"bytes,4,rep,name=context_before,json=contextBefore,proto3" json:"context_before,omitempty"`
	ContextAfter  []string `protobuf:"bytes,5,rep,name=context_after,json=contextAfter,proto3" json:"context_after,omitempty"`
}

func (x *GrepMatch) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GrepMatch) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GrepMatch) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *GrepMatch) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GrepMatch) GetContextBefore() []string {
	if x != nil {
		return x.ContextBefore
	}
	return nil
}

func (x *GrepMatch) GetContextAfter() []string {
	if x != nil {
		return x.ContextAfter
	}
	return nil
}

type GlobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
}

func (x *GlobRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GlobRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type GlobResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *GlobResults) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *GlobResults) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// History messages
type HistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path  string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Limit int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HistoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type VersionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Versions []*VersionInfo `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
}

func (x *VersionList) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *VersionList) GetVersions() []*VersionInfo {
	if x != nil {
		return x.Versions
	}
	return nil
}

type VersionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Author    string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Message   string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *VersionInfo) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *VersionInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VersionInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *VersionInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VersionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DiffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version1 int32  `protobuf:"varint,2,opt,name=version1,proto3" json:"version1,omitempty"`
	Version2 int32  `protobuf:"varint,3,opt,name=version2,proto3" json:"version2,omitempty"`
}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DiffRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiffRequest) GetVersion1() int32 {
	if x != nil {
		return x.Version1
	}
	return 0
}

func (x *DiffRequest) GetVersion2() int32 {
	if x != nil {
		return x.Version2
	}
	return 0
}

type DiffResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diff string `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
}

func (x *DiffResult) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *DiffResult) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

type RevertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Author  string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *RevertRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RevertRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RevertRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RevertRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

// Tag messages
type TagRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path   string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Tag    string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *TagRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *TagRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TagRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type TagListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *TagListRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *TagListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type TagListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *TagListResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Link messages
type LinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To     string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Tag    string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Author string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LinkRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *LinkRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *LinkRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *LinkRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type UnlinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *UnlinkRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *UnlinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnlinkRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type LinkListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *LinkListRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LinkListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Tag  string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *Link) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Link) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Link) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type LinkListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*Link `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *LinkListResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LinkListResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Entity messages
type EntityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Path      string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *EntityRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EntityRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type EntityWriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Path      string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Value     []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Author    string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *EntityWriteRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *EntityWriteRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EntityWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EntityWriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *EntityWriteRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Path      string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Value     []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Entity) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Entity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Entity) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Entity) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entity) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type EntityListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prefix    string `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *EntityListRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *EntityListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EntityListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type EntityListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *EntityListResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *EntityListResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Event messages
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventTypes []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type EmitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path     string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *EmitRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EmitRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// go:plugin type=host
// Host provides all host API operations to plugins.
type Host interface {
	// Document operations
	DocumentRead(context.Context, *ReadRequest) (*Document, error)
	DocumentWrite(context.Context, *WriteRequest) (*Document, error)
	DocumentEdit(context.Context, *EditRequest) (*Document, error)
	DocumentDelete(context.Context, *DeleteRequest) (*Empty, error)
	DocumentRestore(context.Context, *RestoreRequest) (*Document, error)
	DocumentList(context.Context, *ListRequest) (*DocumentListResponse, error)
	DocumentMove(context.Context, *MoveRequest) (*Document, error)
	DocumentExists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	// Search operations
	SearchFullText(context.Context, *SearchRequest) (*SearchResults, error)
	SearchRegex(context.Context, *GrepRequest) (*GrepResults, error)
	SearchGlob(context.Context, *GlobRequest) (*GlobResults, error)
	// History operations
	HistoryList(context.Context, *HistoryRequest) (*VersionList, error)
	HistoryDiff(context.Context, *DiffRequest) (*DiffResult, error)
	HistoryRevert(context.Context, *RevertRequest) (*Document, error)
	// Tag operations
	TagAdd(context.Context, *TagRequest) (*Empty, error)
	TagRemove(context.Context, *TagRequest) (*Empty, error)
	TagList(context.Context, *TagListRequest) (*TagListResponse, error)
	// Link operations
	LinkAdd(context.Context, *LinkRequest) (*Link, error)
	LinkRemove(context.Context, *UnlinkRequest) (*Empty, error)
	LinkList(context.Context, *LinkListRequest) (*LinkListResponse, error)
	// Entity operations (for plugin state)
	EntityRead(context.Context, *EntityRequest) (*Entity, error)
	EntityWrite(context.Context, *EntityWriteRequest) (*Entity, error)
	EntityDelete(context.Context, *EntityRequest) (*Empty, error)
	EntityList(context.Context, *EntityListRequest) (*EntityListResponse, error)
	// Event operations
	EventSubscribe(context.Context, *SubscribeRequest) (*Empty, error)
	EventEmit(context.Context, *EmitRequest) (*Empty, error)
}
