// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.21.12
// source: plugin/plugin.proto

package plugin

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Interface int32

const (
	Interface_INTERFACE_CLI Interface = 0
	Interface_INTERFACE_MCP Interface = 1
	Interface_INTERFACE_API Interface = 2
)

// Enum value maps for Interface.
var (
	Interface_name = map[int32]string{
		0: "INTERFACE_CLI",
		1: "INTERFACE_MCP",
		2: "INTERFACE_API",
	}
	Interface_value = map[string]int32{
		"INTERFACE_CLI": 0,
		"INTERFACE_MCP": 1,
		"INTERFACE_API": 2,
	}
)

func (x Interface) Enum() *Interface {
	p := new(Interface)
	*p = x
	return p
}

type OutputFormat int32

const (
	OutputFormat_FORMAT_TEXT  OutputFormat = 0
	OutputFormat_FORMAT_JSON  OutputFormat = 1
	OutputFormat_FORMAT_TABLE OutputFormat = 2
)

// Enum value maps for OutputFormat.
var (
	OutputFormat_name = map[int32]string{
		0: "FORMAT_TEXT",
		1: "FORMAT_JSON",
		2: "FORMAT_TABLE",
	}
	OutputFormat_value = map[string]int32{
		"FORMAT_TEXT":  0,
		"FORMAT_JSON":  1,
		"FORMAT_TABLE": 2,
	}
)

func (x OutputFormat) Enum() *OutputFormat {
	p := new(OutputFormat)
	*p = x
	return p
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostVersion string `protobuf:"bytes,1,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InitRequest) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

type Manifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version          string     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Author           string     `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Description      string     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MinHostVersion   string     `protobuf:"bytes,5,opt,name=min_host_version,json=minHostVersion,proto3" json:"min_host_version,omitempty"`
	Commands         []*Command `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	SubscribedEvents []string   `protobuf:"bytes,7,rep,name=subscribed_events,json=subscribedEvents,proto3" json:"subscribed_events,omitempty"`
}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetMinHostVersion() string {
	if x != nil {
		return x.MinHostVersion
	}
	return ""
}

func (x *Manifest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Manifest) GetSubscribedEvents() []string {
	if x != nil {
		return x.SubscribedEvents
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Usage       string  `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	Flags       []*Flag `protobuf:"bytes,4,rep,name=flags,proto3" json:"flags,omitempty"`
	McpEnabled  bool    `protobuf:"varint,5,opt,name=mcp_enabled,json=mcpEnabled,proto3" json:"mcp_enabled,omitempty"`
	McpName     string  `protobuf:"bytes,6,opt,name=mcp_name,json=mcpName,proto3" json:"mcp_name,omitempty"`
}

func (x *Command) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Command) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Command) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Command) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *Command) GetFlags() []*Flag {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *Command) GetMcpEnabled() bool {
	if x != nil {
		return x.McpEnabled
	}
	return false
}

func (x *Command) GetMcpName() string {
	if x != nil {
		return x.McpName
	}
	return ""
}

type Flag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Short       string `protobuf:"bytes,2,opt,name=short,proto3" json:"short,omitempty"`
	Type        string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // string, int, bool, stringSlice
	Default     string `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Required    bool   `protobuf:"varint,6,opt,name=required,proto3" json:"required,omitempty"`
}

func (x *Flag) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Flag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Flag) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

func (x *Flag) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Flag) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Flag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Flag) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type CommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string            `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string          `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Flags   map[string]string `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Context *ExecutionContext `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Stdin   []byte            `protobuf:"bytes,5,opt,name=stdin,proto3" json:"stdin,omitempty"`
}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *CommandRequest) GetFlags() map[string]string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *CommandRequest) GetContext() *ExecutionContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommandRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

type ExecutionContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface Interface         `protobuf:"varint,1,opt,name=interface,proto3,enum=llmd.plugin.Interface" json:"interface,omitempty"`
	Author    string            `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Format    OutputFormat      `protobuf:"varint,3,opt,name=format,proto3,enum=llmd.plugin.OutputFormat" json:"format,omitempty"`
	Env       map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ExecutionContext) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *ExecutionContext) GetInterface() Interface {
	if x != nil {
		return x.Interface
	}
	return Interface_INTERFACE_CLI
}

func (x *ExecutionContext) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ExecutionContext) GetFormat() OutputFormat {
	if x != nil {
		return x.Format
	}
	return OutputFormat_FORMAT_TEXT
}

func (x *ExecutionContext) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output  string       `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Format  OutputFormat `protobuf:"varint,3,opt,name=format,proto3,enum=llmd.plugin.OutputFormat" json:"format,omitempty"`
	Error   string       `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResponse) GetFormat() OutputFormat {
	if x != nil {
		return x.Format
	}
	return OutputFormat_FORMAT_TEXT
}

func (x *CommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string            `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path      string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Version   int32             `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Author    string            `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Timestamp int64             `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata  map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Event) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Event) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// go:plugin type=plugin version=1
// Plugin is the interface that all llmd plugins must implement.
// The host calls these methods to interact with the plugin.
type Plugin interface {
	// Init is called once when the plugin loads. Returns the plugin manifest.
	Init(context.Context, *InitRequest) (*Manifest, error)
	// ExecuteCommand executes a command and returns the result.
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
	// HandleEvent is called when a subscribed event occurs.
	HandleEvent(context.Context, *Event) (*Empty, error)
	// Shutdown is called when the plugin is being unloaded.
	Shutdown(context.Context, *Empty) (*Empty, error)
}
