// Package host provides the plugin host framework for llmd.
//
// This package is responsible for the plugin lifecycle: loading WASM plugins,
// initialising them, routing commands to the appropriate plugin, and cleaning
// up when the host shuts down.
//
// # Architecture
//
// The host uses a WebAssembly-based plugin system built on:
//   - github.com/knqyf263/go-plugin: Protocol Buffers-based plugin framework
//   - github.com/tetratelabs/wazero: Pure Go WebAssembly runtime
//
// Plugins are compiled as WASM modules with -buildmode=c-shared (reactor modules).
// The host loads each plugin, instantiates WASI for system calls, and exports
// host functions that plugins can call to access the document store.
//
// # Plugin Loading Order
//
// Plugins are loaded in priority order:
//  1. Embedded plugins: Compiled into the binary (e.g., core plugin)
//  2. Bundled plugins: Same directory as the llmd binary
//  3. Global plugins: ~/.llmd/plugins/
//  4. Project plugins: .llmd/plugins/ (can override embedded)
//
// Later plugins can override earlier ones by providing commands with the same name.
//
// # Usage
//
// Create a host, load plugins, then execute commands:
//
//	ctx := context.Background()
//	store, _ := llmd.Open("")
//
//	h, err := host.New(ctx, store)
//	if err != nil {
//	    return err
//	}
//	defer h.Close(ctx)
//
//	if err := h.LoadPlugins(ctx); err != nil {
//	    return err
//	}
//
//	resp, err := h.ExecuteCommand(ctx, "cat", []string{"docs/readme"}, nil, nil, "user")
package host

import (
	"context"
	"fmt"

	"github.com/jpl-au/llmd/internal/debug"
	"github.com/jpl-au/llmd/internal/llmd"
	"github.com/jpl-au/llmd/internal/paths"
	"github.com/jpl-au/llmd/proto/plugin"
)

// Host is the plugin host that manages plugin lifecycle and command routing.
//
// The Host coordinates all plugin operations: loading plugins from various sources,
// initialising them with the appropriate runtime, tracking registered commands,
// and routing command execution to the correct plugin.
//
// Host is safe for concurrent use from multiple goroutines.
type Host struct {
	// store is the llmd document store that plugins can access.
	store *llmd.Store

	// runtime manages the wazero runtime and plugin loading.
	runtime *Runtime

	// plugins is the list of loaded plugins in load order.
	plugins []*LoadedPlugin

	// commands maps command names to their registrations.
	// Later-loaded plugins can override commands from earlier plugins.
	commands map[string]*RegisteredCommand
}

// LoadedPlugin represents a plugin that has been loaded and initialised.
//
// Each LoadedPlugin contains the plugin's metadata (from its manifest) and
// holds a reference to the WASM instance for command execution.
type LoadedPlugin struct {
	// Name is the plugin's unique identifier from its manifest.
	Name string

	// Version is the plugin's version string from its manifest.
	Version string

	// Source indicates where the plugin was loaded from:
	// "embedded", "bundled", "global", or "project".
	Source string

	// instance is the loaded WASM plugin instance.
	instance pluginInstance
}

// pluginInstance defines the interface for interacting with a loaded plugin.
// This matches the interface generated by go-plugin from the proto definition.
type pluginInstance interface {
	// Init initialises the plugin and returns its manifest.
	Init(ctx context.Context, req *plugin.InitRequest) (*plugin.Manifest, error)

	// ExecuteCommand executes a command and returns the result.
	ExecuteCommand(ctx context.Context, req *plugin.CommandRequest) (*plugin.CommandResponse, error)

	// HandleEvent delivers an event to the plugin.
	HandleEvent(ctx context.Context, req *plugin.Event) (*plugin.Empty, error)

	// Shutdown gracefully shuts down the plugin.
	Shutdown(ctx context.Context, req *plugin.Empty) (*plugin.Empty, error)

	// Close releases resources associated with the plugin.
	Close(ctx context.Context) error
}

// RegisteredCommand maps a command name to its providing plugin.
//
// When a command is executed, the Host looks up the RegisteredCommand and
// forwards the request to the appropriate plugin.
type RegisteredCommand struct {
	// Name is the command name as typed by the user.
	Name string

	// Description is shown in help text.
	Description string

	// Usage shows command syntax (e.g., "cat <path>").
	Usage string

	// Plugin is the plugin that provides this command.
	Plugin *LoadedPlugin

	// MCPEnabled indicates whether this command is exposed via MCP.
	MCPEnabled bool

	// MCPName overrides the MCP tool name (defaults to Name).
	MCPName string

	// Flags defines the command's accepted flags.
	Flags []*plugin.Flag
}

// New creates a new plugin host.
//
// The host initialises a wazero runtime with WASI support and host functions
// that allow plugins to access the document store. After creating the host,
// call LoadPlugins to load available plugins.
//
// The store parameter can be nil for discovery commands (help, plugins) that
// only need to load plugin manifests. If store is nil, any plugin that calls
// host functions during ExecuteCommand will receive ErrStoreNotAvailable.
//
// The caller must call Close when finished with the host.
func New(ctx context.Context, store *llmd.Store) (*Host, error) {
	runtime, err := NewRuntime(ctx, store)
	if err != nil {
		return nil, fmt.Errorf("creating runtime: %w", err)
	}

	return &Host{
		store:    store,
		runtime:  runtime,
		plugins:  make([]*LoadedPlugin, 0),
		commands: make(map[string]*RegisteredCommand),
	}, nil
}

// LoadPlugins loads plugins from all standard locations.
//
// Plugins are loaded in priority order. Later plugins can override commands
// from earlier plugins. For example, a project-specific core.wasm in
// .llmd/plugins/ will override the embedded core plugin.
//
// The loading order is:
//  1. Embedded plugins (compiled into the binary)
//  2. Global plugins (~/.llmd/plugins/)
//  3. Project plugins (.llmd/plugins/)
func (h *Host) LoadPlugins(ctx context.Context) error {
	// 1. Load embedded core plugin (must succeed)
	if err := h.load(ctx, PluginEmbed, "core"); err != nil {
		return fmt.Errorf("loading core plugin: %w", err)
	}

	// 2. Load global plugins (~/.llmd/plugins/) - warn on failure
	if globalDir, err := paths.GlobalDir(); err == nil {
		h.load(ctx, PluginDir, globalDir+"/plugins")
	}

	// 3. Load project plugins (.llmd/plugins/) - warn on failure
	h.load(ctx, PluginDir, ".llmd/plugins")

	return nil
}

// ExecuteCommand finds and executes a command by name.
//
// The command is looked up in the registered commands and forwarded to the
// appropriate plugin. The args slice contains positional arguments, the
// flags map contains parsed flag values, stdin contains any piped input,
// and author identifies who is executing the command.
//
// Returns the full CommandResponse containing both text and structured output,
// or an error if the command is not found or execution fails.
func (h *Host) ExecuteCommand(ctx context.Context, name string, args []string, flags map[string]any, stdin []byte, author string) (*plugin.CommandResponse, error) {
	debug.Log("ExecuteCommand", "command", name, "args", args)

	cmd, ok := h.commands[name]
	if !ok {
		debug.Log("ExecuteCommand error", "error", "unknown command")
		return nil, fmt.Errorf("unknown command: %s", name)
	}

	// Convert flags to string map
	flagsStr := make(map[string]string)
	for k, v := range flags {
		flagsStr[k] = fmt.Sprintf("%v", v)
	}

	// Call the plugin
	debug.Log("ExecuteCommand", "step", "calling plugin", "plugin", cmd.Plugin.Name)
	resp, err := cmd.Plugin.instance.ExecuteCommand(ctx, &plugin.CommandRequest{
		Command: name,
		Args:    args,
		Flags:   flagsStr,
		Stdin:   stdin,
		Context: &plugin.ExecutionContext{
			Interface: plugin.Interface_INTERFACE_CLI,
			Author:    author,
		},
	})
	if err != nil {
		debug.Log("ExecuteCommand error", "error", err.Error())
		return nil, fmt.Errorf("executing command: %w", err)
	}

	debug.Log("ExecuteCommand", "step", "plugin returned", "success", resp.Success)
	if !resp.Success {
		return nil, fmt.Errorf("command failed: %s", resp.Error)
	}

	return resp, nil
}

// Close shuts down all plugins and releases resources.
//
// Each plugin's Shutdown method is called to allow graceful cleanup, then
// the plugin instance is closed. This should be called when the host is
// no longer needed.
func (h *Host) Close(ctx context.Context) error {
	for _, p := range h.plugins {
		p.instance.Shutdown(ctx, &plugin.Empty{})
		p.instance.Close(ctx)
	}
	return nil
}

// Store returns the underlying llmd document store.
//
// This provides direct access to the store for operations that don't go
// through plugins.
func (h *Host) Store() *llmd.Store {
	return h.store
}

// Commands returns all registered commands.
//
// The returned map is keyed by command name. Commands from later-loaded
// plugins may have overridden earlier commands.
func (h *Host) Commands() map[string]*RegisteredCommand {
	return h.commands
}

// Plugins returns all loaded plugins in load order.
func (h *Host) Plugins() []*LoadedPlugin {
	return h.plugins
}
